In [ ]:
# Assignment 2
# Name: Sumit Kumar Tapa
# Reg No: 24-14-18
# Programme: M Tech Modeling and Simulation

In [1]:
# Q1

import numpy as np

#a
print("Q1, a")
var1 = np.arange(31)
print(var1, "\nshape: ",  var1.shape)

#b
print("\nQ1, b")
var2 = np.concatenate((var1, np.array([0]))).reshape(4,8)
print(var2, "\nshape: ", var2.shape)

#c
print("\nQ1, c")
var3 = var2.reshape(2,4,4)
print(var3, "\nshape: ", var3.shape)

Q1, a
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
shape:  (31,)

Q1, b
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30  0]] 
shape:  (4, 8)

Q1, c
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30  0]]] 
shape:  (2, 4, 4)


In [2]:
#d
print("\nQ1, d")
var2[1][0] = -1
print("var1: ", var1, "\nvar2: ", var2, "\nvar3: ", var3)
print("\nVar1 is not changed. Var3 has changed.\nReshape returns a view of numpy array")



Q1, d
var1:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30] 
var2:  [[ 0  1  2  3  4  5  6  7]
 [-1  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30  0]] 
var3:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [-1  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30  0]]]

Var1 is not changed. Var3 has changed.
Reshape returns a view of numpy array


In [3]:
#e
print("\nQ1, e")
print("sum over 2nd dimension: ", np.sum(var3, axis=1))
print("sum over 3rd dimension: ", np.sum(var3, axis=2))
print("sum over 1st and 3rd dimension: ", np.sum(var3, axis=(0,2)))

#f
print("\nQ1, f")
var2_second_row = var2[1, :]
print("var2 second row:", var2_second_row)

var2_last_column = var2[:, -1]
print("var2_last_column: ", var2_last_column)

var2_sub_matrix = var2[0:2, 0:2]
print("var2_sub_matrix: ", var2_sub_matrix)


Q1, e
sum over 2nd dimension:  [[15 28 32 36]
 [88 92 96 69]]
sum over 3rd dimension:  [[  6  22  29  54]
 [ 70  86 102  87]]
sum over 1st and 3rd dimension:  [ 76 108 131 141]

Q1, f
var2 second row: [-1  9 10 11 12 13 14 15]
var2_last_column:  [ 7 15 23  0]
var2_sub_matrix:  [[ 0  1]
 [-1  9]]


In [4]:
#Q2

#a
print("\nQ2, a")
vect1 = np.arange(0,10)
vect2 = vect1 + 1
print(vect2)

#b
print("\nQ2, b")

vect3 = np.arange(0)
for i in range(10):
    vect3 = np.concatenate((vect3, vect1+i))

vect3 = vect3.reshape(10,10)
print(vect3)

#c
print("\nQ2, c")
import numpy.random as npr
dataset1 = np.exp(npr.randn(50, 5))
print("dataset with 50 examples: ", dataset1.shape)

#e
print("\nQ2, e")
dataset1_mean = np.sum(dataset1, axis=0)/50
print("mean: ", dataset1_mean)

dataset1_std = np.std(dataset1, axis=0)
print("standard deviation: ", dataset1_std)

#f
print("\nQ2, f")
normalized = dataset1 - dataset1_mean
normalized = normalized / dataset1_std
print("normalized mean: ",np.sum(normalized, axis=0)/50)
print("normalized std deviation: ", np.std(normalized, axis=0))


Q2, a
[ 1  2  3  4  5  6  7  8  9 10]

Q2, b
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]

Q2, c
dataset with 50 examples:  (50, 5)

Q2, e
mean:  [1.17605605 2.09684506 1.55661865 1.42500886 1.83549915]
standard deviation:  [1.38553188 2.83799906 2.1310474  1.46556288 2.73781468]

Q2, f
normalized mean:  [ 2.22044605e-18 -2.88657986e-17  2.22044605e-18 -8.65973959e-17
 -1.93178806e-16]
normalized std deviation:  [1. 1. 1. 1. 1.]


In [8]:
#Q3

def vandermonde(N):
    vec = np.arange(N) + 1

    vander = np.power(vec[:, None], np.arange(N))
    return vander

#a
print("\nQ3, a")
vander = vandermonde(12)
print(vander)



Q3, a
[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543

In [9]:
#b
print("\nQ3, b")
x = np.ones(12)
b = np.dot(vander, x)
print("b: ", b)

#c
print("\nQ3, c")
v = np.linalg.inv(vander)
res1 = np.dot(v, b)
print(res1)
print("""There is difference than what is expected.
Since we know x is of ones, it is expected, but have got only few values as 1 (or approximate 1)""")

#d
print("\nQ3, d")
res2 = np.linalg.solve(vander, b)
print(res2)


Q3, b
b:  [1.20000000e+01 4.09500000e+03 2.65720000e+05 5.59240500e+06
 6.10351560e+07 4.35356467e+08 2.30688120e+09 1.22713351e+09
 9.43953692e+08 3.73692871e+09 3.10225064e+08 3.10073456e+09]

Q3, c
[0.99620819 1.00462723 0.99909973 1.00006104 0.99999666 1.00000048
 0.99999995 1.         1.         1.         1.         1.        ]
There is difference than what is expected.
Since we know x is of ones, it is expected, but have got only few values as 1 (or approximate 1)

Q3, d
[0.99998827 1.00002951 0.99997139 1.00001427 0.99999595 1.00000068
 0.99999993 1.         1.         1.         1.         1.        ]
